spring.application.name=gigweb
spring.datasource.url=jdbc:mysql://localhost:3306/sys
spring.datasource.username=root
spring.datasource.password=Udham@090804

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
